name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Build and deploy to Cloudflare Workers
        run: |
          wrangler login # You will be prompted to login to your Cloudflare account
          wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # Ensure you have added CF_API_TOKEN as a secret in your repository settings
