include: 
  - remote: "https://raw.githubusercontent.com/eidam/gitlab-wrangler-action/main/templates/1.3.0.yml"

stages:
  - deploy

wrangler deploy:
  extends: .wrangler_deploy
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
